



services:
  drupal:
    image: drupal:9
    port:
     - 8080:80
    vloums:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
  postgres: 
    image: postgres:14
    environment:
      -POSTGRES_PASSWORD=melika
